import {BOSSES,ELEMENTS,SPELLS,RUNES,type Element,type Rune} from './config';
import type {Game} from './game';
import type {GameRenderer} from './render';
import type {AudioManager} from './audio';
import type {GameEvent} from './core';
const $=(id:string)=>document.getElementById(id)!;
export class UI {
 warningTime=0;comboTime=0;announcementTime=0;lastState='';loadoutHand:0|1=0;previous:'menu'|'playing'='menu';
 constructor(public g:Game,public view:GameRenderer,public audio:AudioManager){
  $('start').onclick=()=>{g.start();this.resume();};$('howto').onclick=()=>this.controls();$('menu-settings').onclick=()=>this.settings();$('pause-button').onclick=()=>this.pause();
  document.addEventListener('keydown',e=>{if(e.code==='Escape'){if(g.state==='playing')this.pause();else if(g.state==='paused')this.resume();}if(e.code==='Tab'){e.preventDefault();if(g.state==='playing')this.loadout();else if(g.state==='paused')this.resume();}});
 }
 ready(){$('loading').hidden=true;$('menu').hidden=false;if(this.g.best)$('best').textContent=`BEST RUN · ${this.g.best} / 5 GUARDIANS`;}
 resume(){this.g.state='playing';this.lastState='';$('modal').hidden=true;$('menu').hidden=true;$('hud').hidden=false;this.g.input.keys.clear();this.g.input.buttons.clear();this.g.input.pressed.clear();this.audio.start();try{const promise=this.view.canvas.requestPointerLock();if(promise)promise.catch(()=>{});}catch{}}
 pause(){if(this.g.state!=='playing')return;this.g.state='paused';this.release();this.show(`<span class="eyebrow">TAKE A BREATH</span><h2>Between the elements.</h2><p>${BOSSES[this.g.boss.index].tip}</p><div class="modal-actions"><button class="primary" id="resume">RETURN TO THE DUEL <span>→</span></button><button class="text-button" id="settings">SETTINGS</button><button class="text-button" id="controls">CONTROLS</button></div><button class="text-button" id="quit">END RUN & RETURN TO TITLE</button>`);$('resume').onclick=()=>this.resume();$('settings').onclick=()=>this.settings();$('controls').onclick=()=>this.controls();$('quit').onclick=()=>{this.g.state='menu';this.g.save();$('modal').hidden=true;this.lastState='';};}
 release(){if(document.pointerLockElement)document.exitPointerLock();this.g.input.keys.clear();this.g.input.buttons.clear();this.g.input.pressed.clear();}
 show(html:string){$('modal-content').innerHTML=html;$('modal').hidden=false;}
 back(){if(this.g.state==='menu')$('modal').hidden=true;else{this.g.state='playing';this.pause();}}
 controls(){if(this.g.state==='playing'){this.g.state='paused';this.release();}const controls=[['W A S D','Move'],['MOUSE','Aim / look'],['SHIFT','Sprint'],['SPACE','Jump / double jump'],['HOLD SPACE','Levitate / glide'],['C or ALT','Directional air / ground dodge'],['CTRL','Slide'],['LEFT / RIGHT MOUSE','Left / right primary spell'],['Q / E','Left / right secondary'],['F','Elemental overdrive (100%)'],['R','Movement rune'],['1 / 2','Cycle left / right element'],['TAB','Gauntlets & rune loadout'],['L','Toggle boss lock-on'],['ESC','Pause']];this.show(`<span class="eyebrow">FAST MOVEMENT. ELEMENTAL COMBINATIONS.</span><h2>Become the storm.</h2><p>Hold the mouse buttons to cast. Attacks never stop movement. Apply frost, then fire for Thermal Shock. Jump above red ground attacks. Ride the rising mint rings to gain altitude.</p><div class="controls">${controls.map(([key,action])=>`<div class="control"><span>${action}</span><kbd>${key}</kbd></div>`).join('')}</div><p>Desktop keyboard and mouse required. Click the arena to capture the mouse. If pointer capture is unavailable, move the pointer across the arena to aim.</p><button class="primary" id="back">UNDERSTOOD <span>→</span></button>`);$('back').onclick=()=>this.back();}
 settings(){if(this.g.state==='playing'){this.g.state='paused';this.release();}this.show(`<span class="eyebrow">MAKE IT YOURS</span><h2>Settings</h2><label class="settings-row">Field of view <input id="fov" type="range" min="60" max="100" value="${this.view.fov}" /></label><label class="settings-row">Sound volume <input id="volume" type="range" min="0" max="100" value="${this.audio.volume*100}" /></label><label class="settings-row">Camera shake <input id="shake" type="checkbox" ${this.view.shakeEnabled?'checked':''} /></label><label class="settings-row">Bloom effects <input id="bloom" type="checkbox" ${this.view.quality?'checked':''} /></label><label class="settings-row">Challenge <select id="difficulty"><option value="0.6" ${this.g.difficulty===.6?'selected':''}>Wayfarer · gentler damage</option><option value="1" ${this.g.difficulty===1?'selected':''}>Battlemage · standard</option><option value="1.4" ${this.g.difficulty===1.4?'selected':''}>Archmage · unforgiving</option></select></label><button class="primary" id="back">SAVE & RETURN <span>→</span></button>`);
  ($('fov') as HTMLInputElement).oninput=e=>this.view.fov=Number((e.target as HTMLInputElement).value);($('volume') as HTMLInputElement).oninput=e=>this.audio.setVolume(Number((e.target as HTMLInputElement).value)/100);($('shake') as HTMLInputElement).onchange=e=>this.view.shakeEnabled=(e.target as HTMLInputElement).checked;($('bloom') as HTMLInputElement).onchange=e=>this.view.quality=(e.target as HTMLInputElement).checked;($('difficulty') as HTMLSelectElement).onchange=e=>this.g.difficulty=Number((e.target as HTMLSelectElement).value);$('back').onclick=()=>{try{localStorage.setItem('riftborne-settings',JSON.stringify({fov:this.view.fov,volume:this.audio.volume,shake:this.view.shakeEnabled,bloom:this.view.quality,difficulty:this.g.difficulty}));}catch{}this.back();};
 }
 loadout(){this.g.state='paused';this.release();const draw=()=>{this.show(`<span class="eyebrow">TWO HANDS. ENDLESS POSSIBILITIES.</span><h2>Your arsenal</h2><div class="loadout-title"><button id="hand-left" class="${this.loadoutHand===0?'active':''}">LEFT · ${this.g.player.hands[0].toUpperCase()}</button><button id="hand-right" class="${this.loadoutHand===1?'active':''}">RIGHT · ${this.g.player.hands[1].toUpperCase()}</button></div><div class="loadout-grid">${ELEMENTS.map((e,i)=>`<button class="element-choice ${this.g.player.hands[this.loadoutHand]===e?'selected':''}" data-element="${e}"><div class="element-art" style="background-position:${i%3*50}% ${i<3?0:100}%"></div><strong>${e.toUpperCase()}</strong><small>${SPELLS[e].name}</small></button>`).join('')}</div><p>${SPELLS[this.g.player.hands[this.loadoutHand]].passive}. Combine different elements on an enemy or in a lingering spell zone to trigger a reaction.</p><label class="settings-row">Movement rune <select id="rune">${RUNES.map(r=>`<option ${r===this.g.player.rune?'selected':''}>${r}</option>`).join('')}</select></label><button class="primary" id="resume">RETURN TO THE DUEL <span>→</span></button>`);$('hand-left').onclick=()=>{this.loadoutHand=0;draw();};$('hand-right').onclick=()=>{this.loadoutHand=1;draw();};document.querySelectorAll<HTMLButtonElement>('[data-element]').forEach(b=>b.onclick=()=>{this.g.player.hands[this.loadoutHand]=b.dataset.element as Element;draw();});($('rune') as HTMLSelectElement).onchange=e=>this.g.player.rune=(e.target as HTMLSelectElement).value as Rune;$('resume').onclick=()=>this.resume();};draw();}
 event(e:GameEvent){if(e.type==='warning'){$('warning').textContent=e.text||'';this.warningTime=2;}
  if(e.type==='combo'||e.type==='pickup'){$('combo').textContent=e.text||'';this.comboTime=1.6;}
  if(e.type==='phase'){$('announcement').querySelector('span')!.textContent='THE FIVEFOLD TRIAL';$('announcement').querySelector('h2')!.textContent=e.text||'';this.announcementTime=3;}
  if(e.type==='hit'&&!e.pos){$('damage-flash').style.opacity='.65';setTimeout(()=>$('damage-flash').style.opacity='0',120);}
 }
 update(dt:number){const g=this.g,p=g.player,b=g.boss,d=BOSSES[b.index];this.warningTime-=dt;this.comboTime-=dt;this.announcementTime-=dt;$('warning').style.opacity=this.warningTime>0?'1':'0';$('combo').style.opacity=this.comboTime>0?'1':'0';$('announcement').style.opacity=this.announcementTime>0?'1':'0';
  if(this.lastState!==g.state){this.lastState=g.state;$('menu').hidden=g.state!=='menu';$('hud').hidden=g.state==='menu';if(g.state==='dead'||g.state==='won'){this.release();this.show(`<span class="eyebrow">${g.state==='won'?'ALL FIVE GUARDIANS DEFEATED':'THE RIFT REMEMBERS'}</span><h2>${g.state==='won'?'The elements are yours.':'Rise. Reforge. Return.'}</h2><p>${g.state==='won'?'You have broken the Fivefold Trial. A new build is a new way through.':d.tip}</p><div class="stats"><div>${b.index+(b.dead?1:0)} / 5<small>GUARDIANS</small></div><div>${g.combat.comboCount}<small>ELEMENTAL COMBOS</small></div><div>${this.time(g.runTime)}<small>RUN TIME</small></div></div><button class="primary" id="restart">RUN AGAIN <span>→</span></button><button class="text-button" id="title">RETURN TO TITLE</button>`);$('restart').onclick=()=>{g.start();this.resume();};$('title').onclick=()=>{g.state='menu';$('modal').hidden=true;};}
   if(g.state==='upgrade'){this.release();this.show(`<span class="eyebrow">GUARDIAN ${b.index+1} DEFEATED · YOUR POWER GROWS</span><h2>Choose your evolution.</h2><p>Take one upgrade into ${BOSSES[Math.min(4,b.index+1)].biome.toLowerCase()}. Health is restored between realms.</p><div class="upgrade-grid">${g.choices.map(u=>`<button class="upgrade" data-upgrade="${u.id}"><small>${u.kind}</small><h3>${u.name}</h3><p>${u.detail}</p></button>`).join('')}</div>`);document.querySelectorAll<HTMLButtonElement>('[data-upgrade]').forEach(btn=>btn.onclick=()=>{g.selectUpgrade(btn.dataset.upgrade!);this.resume();});}
  }
  $('biome').textContent=`0${b.index+1} / 05 · ${d.biome}`;$('objective').textContent=g.bossActive?'DEFEAT THE GUARDIAN':`CLEAR THE GUARDIANS · ${g.enemies.filter(e=>!e.dead).length} REMAIN`;$('boss-name').textContent=d.name;$('boss-phase').textContent=`PHASE ${b.phase} / ${d.phases}`;$('boss-health').style.width=`${b.hp/b.maxHp*100}%`;$('boss-hp').textContent=`${Math.ceil(b.hp).toLocaleString()} / ${b.maxHp.toLocaleString()}`;$('boss-state').textContent=!g.bossActive?'SEALED · DEFEAT THE SENTINELS':b.weak>0?'CORE EXPOSED · STRIKE NOW':b.armor>0?'ARMORED':'ELEMENTAL GUARDIAN';$('health-value').innerHTML=`${Math.ceil(p.hp)} <small>/ ${p.maxHp}</small>`;$('health').style.width=`${p.hp/p.maxHp*100}%`;$('energy').style.width=`${p.energy}%`;$('timer').textContent=this.time(g.runTime);$('dodge-label').textContent=p.dodge>0?`DODGE · ${p.dodge.toFixed(1)}s`:'C · AIR DODGE';$('rune-label').textContent=p.runeCD>0?`${p.rune.toUpperCase()} · ${p.runeCD.toFixed(1)}s`:`R · ${p.rune.toUpperCase()}`;$('overdrive').classList.toggle('ready',p.ultimate>=100);$('overdrive').querySelector('i')!.style.width=`${p.ultimate}%`;$('overdrive').querySelector('b')!.textContent=p.ultimate>=100?'READY':`${Math.floor(p.ultimate)}%`;$('lock-label').hidden=!g.lockOn;
  for(let i=0;i<2;i++){const e=p.hands[i],index=ELEMENTS.indexOf(e),el=$(i===0?'left-gauntlet':'right-gauntlet');el.style.setProperty('--element',`#${SPELLS[e].color.toString(16).padStart(6,'0')}`);el.querySelector('strong')!.textContent=e.toUpperCase();(el.querySelector('.element-art') as HTMLElement).style.backgroundPosition=`${index%3*50}% ${index<3?0:100}%`;el.querySelector('span')!.textContent=`${i===0?'Q':'E'} · ${SPELLS[e].name.toUpperCase()}`;el.querySelector('.cooldown')!.textContent=p.secondary[i]>0?`${p.secondary[i].toFixed(1)}s`:'READY';}
 }
 time(seconds:number){return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${Math.floor(seconds%60).toString().padStart(2,'0')}`;}
}
